### ISSUE TITLE
H6001

### ISSUE THREAD

**Issue by bwp91** [egold555/Govee-H6113-Reverse-Engineering#3]
Hi,

Can confirm that the H6001 uses the same commands for on/off, brightness and colour as the H6127.

This repo has helped me a lot with the development of my homebridge-govee plugin.

So thanks!

**Comment by egold555** [comment]
I have [added a file for the H6001](https://github.com/egold555/Govee-Reverse-Engineering/blob/master/Products/H6001.md) based off this issue. Currently it just sums up this issue and refers people to the [H6127](https://github.com/egold555/Govee-Reverse-Engineering/blob/master/Products/H6127.md) product.

Please let me know if you do any more testing with the H6001 using the H6127's commands!
