### ISSUE TITLE
H5082

### ISSUE THREAD

**Issue by BrettMeirhofer** [egold555/Govee-H6113-Reverse-Engineering#5]
https://www.amazon.com/Govee-Bluetooth-Assistant-Remotely-Certified/dp/B09HKS7MYZ

I need some help with reverse engineering the H5082's. They are wifi/blueprint enabled plugs with two relays. In order to use them with the Govee app you do the standard bluetooth add then press a button on the device to pair. I turned each relay on and off 5 times. I then performed produced a frequency analysis on the bluetooth packets commands my device sent.

{'33b22c27b20b31103b340000000000000000001d': 20, 'aa010000000000000000000000000000000000ab': 20, '3301200000000000000000000000000000000012': 5, '3301100000000000000000000000000000000022': 5, '3301220000000000000000000000000000000010': 5, '3301110000000000000000000000000000000023': 5}

As you can see the commands that appear 5 times each are the relay control commands.  The keep alive packet that other govee devices use appears 20 times. I don't know what the first command that appears 20 times does. 

I've seen each of the relay control commands to the device but I haven't gotten any changes on the relay. Not entirely sure where I should go from here and I could use some assistance.

gatttool commands (in interactive mode after connecting to the device)
char-write-cmd 0x0011 3301200000000000000000000000000000000012 (Might be relay 2 turn off)
char-write-cmd 0x0011 3301100000000000000000000000000000000022 (Might be relay 1 turn off)
char-write-cmd 0x0011 3301220000000000000000000000000000000010 (Might be relay 2 turn on)
char-write-cmd 0x0011 3301110000000000000000000000000000000023 (Might be relay 1 turn on)

**Comment by egold555** [comment]
This product has been mostly reverse engineered thanks to @reydanro 

https://github.com/egold555/Govee-Reverse-Engineering/blob/master/Products/H5080.md

Going to close this issue for now, I can re-open it if needed.
